language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: P+LtJDA0fwylp/PwRE8szLDOHB2Ld+wBNpWqlzfUa5gAkorOfxpM6ZZhKAGG49pnSOUmwVANuasvmSMt6+9vk8rx1cRchb6zxdqXG0lj1ieoTUsRHVj3OFDU7aTvU9PLhSWz27oGGfALK7TEJLZ3lc7OnQVYMXU+2doB6dk7MoA=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: O7unB2c6P1sGH2IDeE2rJp7tpyYladIhiblQxbkJC6lDNY7lbIcOiCgXGUbk45ALO90UGYTUsR85PQjAelHhIko78WTQvemRb76t8OufWEQNyHiZUfCbhi1k1/Tx6xUlBma4K1b/l6nzvThIUzFsqDxGZQet9w34pUFlIFT6lZI=
sudo: false
