language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: B6iY9Hjko5Bai56kwkou9y3Wk+D+omXkidU9QRk2qGnF34Ar18r7UZ9VyaHkDl9cNigHSuDzYqpL2dzT8zGfrrnPOLHjbrWj29N5ZJUEWFMxl34+kxbnkXEa1/fQD9hKccqYkPq4vF2RgwcVvJegrH0hv3z0sM6QKpSpGoyLETY=
notifications:
  email: false
  slack:
    secure: O7unB2c6P1sGH2IDeE2rJp7tpyYladIhiblQxbkJC6lDNY7lbIcOiCgXGUbk45ALO90UGYTUsR85PQjAelHhIko78WTQvemRb76t8OufWEQNyHiZUfCbhi1k1/Tx6xUlBma4K1b/l6nzvThIUzFsqDxGZQet9w34pUFlIFT6lZI=
sudo: false
